name: duanju_app
description: 独立运行的多端短剧应用
publish_to: none
version: 0.1.1+2

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ffi: ^2.2.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
